
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
  - Visual Studio 2017

configuration:
  - Debug

before_build:
  - nuget restore

build:
  project: Resgrid.ApiClient.sln